# SQL code

We will run through some code using MySQL and Python  
The same basic code will work with other SQL databases (PostgreSQL, MariaDB)

In [1]:
import pandas as pd
import sqlalchemy
import pymysql

# Database connection  

I set up MySQL Workbench with a schema I had used for History Lab  
The schema has 12 tables that are connected as in the lecture  

## Important concepts in connecting
1) host name - where is the database you are connecting to stored? Locally? Online?
2) user name - name of the user with access to the SQL server
3) password - password for the user
4) database - which schema are you connecting to?

SQL server can have lots of different schema  
While we can navigate the schema, often schema are self-contained 

Localhosts are referred to either as `localhost` or `127.0.0.1`  
I hardcode the credentials but they should be kept in secure files in most cases

In [2]:
sqlhost = 'localhost'
sqluser='GR5072'
sqlpwd = 'GR_5072'

conn = pymysql.connect(
    host=sqlhost, user=sqluser, password=sqlpwd, db='declassification_pdbs'
)

# Queries

There will always be two steps involved in a query  
1) sending the query to the database (e.g., `cursor.execute()`)
2) retrieving the results back in Python (e.g., `cursor.fetchall()`)

Again, this will be the same across relational databases  
Understanding one makes it easier to understand the others

In [3]:
with conn.cursor() as cursor:
    cursor.execute("SHOW FULL tables;")
    q = cursor.fetchall()
for table in q:
    print(table)

('countries', 'BASE TABLE')
('country_doc', 'BASE TABLE')
('docs', 'BASE TABLE')
('person_doc', 'BASE TABLE')
('persons', 'BASE TABLE')
('tokens', 'BASE TABLE')
('top_countries', 'BASE TABLE')
('top_persons', 'BASE TABLE')
('top_topics', 'BASE TABLE')
('topic_doc', 'BASE TABLE')
('topic_token', 'BASE TABLE')
('topics', 'BASE TABLE')

## Context manager 

As with opening files we will use a context manager to open and close the connection to our database  
Remember that the `with` block will close the file or database connection once the block is complete  
This prevents having too many open connections to the database  

## Query

`cursor.execute()` - sends the query in parentheses to the database  
`cursor.fetchall()` - returns the results to Python

In [4]:
# Get descsription of each column in docs table 
with conn.cursor() as cursor:
    cursor.execute("desc docs;")
    q = cursor.fetchall()
print(q)

(('index', 'bigint', 'YES', 'MUL', None, ''), ('title', 'text', 'YES', '', None, ''), ('doctype', 'text', 'YES', '', None, ''), ('keywords', 'text', 'YES', '', None, ''), ('collection', 'text', 'YES', '', None, ''), ('docno', 'text', 'YES', '', None, ''), ('release_decis', 'text', 'YES', '', None, ''), ('origclass', 'text', 'YES', '', None, ''), ('pages', 'double', 'YES', '', None, ''), ('doccreation', 'datetime', 'YES', '', None, ''), ('docrelease', 'datetime', 'YES', '', None, ''), ('sequenceno', 'double', 'YES', '', None, ''), ('caseno', 'double', 'YES', '', None, ''), ('pubdate', 'datetime', 'YES', '', None, ''), ('file', 'text', 'YES', '', None, ''), ('id', 'text', 'YES', '', None, ''), ('raw_body', 'longtext', 'YES', '', None, ''), ('body', 'longtext', 'YES', '', None, ''), ('redactcode_no', 'double', 'YES', '', None, ''), ('collecttype', 'text', 'YES', '', None, ''))

In [5]:
query = "SELECT * from docs limit 10;"
with conn.cursor() as cursor:
    cursor.execute(query)
    docs = cursor.fetchall()

docs

((0,
  'DAILY SUMMARY - 1946/02/15',
  'SPECIALCOLLECTION',
  None,
  'Daily Summary Collection',
  '3164645',
  None,
  None,
  None,
  datetime.datetime(2018, 8, 3, 0, 0),
  None,
  None,
  None,
  None,
  'https://www.cia.gov/readingroom/docs/DAILY%20SUMMARY%5B15423241%5D.pdf',
  'DOC_0003164645',
  'APPROVED FOR RELEASE - Historical Programs Staff15 March 2018\n \n\x0c\nAPPROVED FOR RELEASE - Historical Programs Staff15 March 2018\n‘ 5 CN se tk\n\\\n(\nge |\ni Sd /4ee\n \nGENERAL\nrae\n“ocret Yalta and Tehran Agreements for Sale in Paris--‘Tine 2aris smbesic,’\nvls0ytS that alleged secret agreements between the US and .he USOR at\n‘alta and Tehran have been offered for sale in Paris by agents of ‘“eome\nEngsians’? in Switverland, und vat a French and a Swiss newspaper are considering their publication. Ambassador Ceffery has secured seme of these\n‘“sovesments’ there are cnid te be eleven.ot them), about which he reports\nine followings .\n \n4. dn one Tehran “agreement” the US promised to supply tne USoR witn\n3 O10 billion credit in return Ior a Soviet corsamitment to support our pron\nnosals for fa: litating world trade, fair distribution of raw materials, and the\nvezulation of international currency.\nbm. In one Yalta “agreement ’, allegedly signed by Hepxins and Molotov,\ntue US recognized a Soviet claim of free access to the Mediterranean in\nroturn for a Soviet agreemen. (1) to recognize the absolute independence of\nAuuleia, Hangary, Czechoslovakia, umania, Bulgaria aud Yugeslav ia ai al\new (2) ty renour ce any agreements -with those countries giving the Scviets a pre-\nmarred position.\nc. Another Yalta “geroement ” covered the Soviet use of German\nprisoners anc Soviet acquisition of German industrial machinery for reconweruction in the USSR.\nIn addition, tae Limbassy reports that these agents are also said to\na QQ\npe offering (a) secret Soviet agrecments witn Syria and Lebanon and iO) 4\ntreaty between Iraq and Transjordan.\n004\nDocument No. ee\nNO Guses in ciassy )\n“‘pEenatsils hs) ©\nnog to: TS §\n \n \nClesge ip vied ave .\nDoh Ienate, cb Bee he\n» Dui Pe 4\nAutn = ; i on\nYY - . 10 Yo ae\n4 bub —O Mar 1979 tz\n \n \n\x0c\nAPPROVED FOR RELEASE - Historical Programs Staff15 March 2018\nww"\nue\noe\na=\n.\n. FRENCH INDOCHINA: Proposed Sino-French agreement--The Chinese\nVONFIDE Tay\nEUROPE-AFRICA\n.\nGERMANY: Discontinuance of relief for displaced persons in US Zone--The\n‘Var Department has authorized Gen. McNarney to announce by 1 March the\ndiscontinuance of relief oy 1 July for all displaced persons in the US Zone in\nGermany. An exception will be made, however, for those perscns who are\nunwilling to be repatriated because of possible persecution on the grounds of\nrace, religion, etc. Those desiring repatriation will be moved out by 1 July.\nTURKEY: USSR willing to wait for solution of Turkish ‘‘problem’’--In conversation with the Turkish Acting Foreign Minister, asreported by Embassy\nAnkara, Soviet Ambassador Vinogradov has stated that ‘‘we waited a long\ntirne regarding the arrangement we wanted with Poland and finally got it; we\ncan walt regarding Turkey.’’ He sald that for a reestablishment of friendly\nveiations between the two countries, a solution of the USSR’s claims regarding the eastern provinxes of Turkey was important, bul ihe question of the\nStraits was ‘‘vital’’. Asked what the Soviet requirements regarding the\nSiralts were, Vinogradov replied thatfthe USSR” (a))must have an adequate\nwuarantee that the security of the Sc viet Union wilt not oe endangered,\n(b) that a sovereign and friendly Turkey at the Straits would not be adequate\nfor the defense of the Straits, and (c) that Soviet use of bases In the Straits\nwhen the need arose would be essential.\nYUGOSLAVIA: Anti-AMG propaganda in Venezia Giulia-- Military autherities\nin Venezia Giulia report that Communist press attachs on the Allied Military\nGovernment are mounting, probably in an effort to obtain UNO examination\nof Allied actions in Venezia Giulia. The authorities also report reinforcements of Yugoslav troops in the Yugoslav zone of the province, apparently\nin order to apply pressure on the local population during the visit of the\nCouncil of Foreign Ministers’ Commission.\n \nFAR EAST .\nCHINA: US moves Chinese armies--CG, Chinese Theatre reports that five\nChinese armies and 18,000 service troops are being moved north by him for\noccupation of Manchuria. in addition to moving this force, he is supplying\n \nthem with 250,000 sets of US winter clothing.\n \nForeign Office has informed Embassy Chungking that negotiations wita\nrence concerning Indochina are in the final stage. Principal provisions\nof the proposed agreement include: (8) witndrawal of Chinese troops, (b) upnolding of prewar Chinese rights, (c) freedom of transportation on the Yunnanfndochina Railway, and elimination of duties through Haiphong.\nae |\n \n\x0c\n',
  ' Historical Programs Staff15 March 2018 5 CN se tk ge i Sd 4ee GENERAL rae “ocret Yalta and Tehran Agreements for Sale in Paris--‘Tine 2aris smbesic,’ vls0ytS that alleged secret agreements between the US and .he USOR at ‘alta and Tehran have been offered for sale in Paris by agents of ‘“eome Engsians’? in Switverland, und vat a French and a Swiss newspaper are considering their publication. Ambassador Ceffery has secured seme of these ‘“sovesments’ there are cnid te be eleven.ot them), about which he reports ine followings 4. dn one Tehran “agreement” the US promised to supply tne USoR witn 3 O10 billion credit in return Ior a Soviet corsamitment to support our pron nosals for fa: litating world trade, fair distribution of raw materials, and the vezulation of international currency. bm. In one Yalta “agreement allegedly signed by Hepxins and Molotov, tue US recognized a Soviet claim of free access to the Mediterranean in roturn for a Soviet agreemen. (1) to recognize the absolute independence of Auuleia, Hangary, Czechoslovakia, umania, Bulgaria aud Yugeslav ia ai al ew (2) ty renour ce any agreements -with those countries giving the Scviets a premarred position. c. Another Yalta “geroement covered the Soviet use of German prisoners anc Soviet acquisition of German industrial machinery for reconweruction in the USSR. In addition, tae Limbassy reports that these agents are also said to a QQ pe offering (a) secret Soviet agrecments witn Syria and Lebanon and iO) 4 treaty between Iraq and Transjordan. 004 Document No. ee NO Guses in ciassy “‘pEenatsils hs) nog to: TS Clesge ip vied ave Doh Ienate, cb Bee he Dui Pe 4 Autn i on YY 10 Yo ae 4 bub —O Mar 1979 tz ww" ue oe a= FRENCH INDOCHINA: Proposed Sino-French agreement--The Chinese VONFIDE Tay EUROPE-AFRICA GERMANY: Discontinuance of relief for displaced persons in US Zone--The ‘Var Department has authorized Gen. McNarney to announce by 1 March the discontinuance of relief oy 1 July for all displaced persons in the US Zone in Germany. An exception will be made, however, for those perscns who are unwilling to be repatriated because of possible persecution on the grounds of race, religion, etc. Those desiring repatriation will be moved out by 1 July. TURKEY: USSR willing to wait for solution of Turkish ‘‘problem’’--In conversation with the Turkish Acting Foreign Minister, asreported by Embassy Ankara, Soviet Ambassador Vinogradov has stated that ‘‘we waited a long tirne regarding the arrangement we wanted with Poland and finally got it; we can walt regarding Turkey.’’ He sald that for a reestablishment of friendly veiations between the two countries, a solution of the USSR’s claims regarding the eastern provinxes of Turkey was important, bul ihe question of the Straits was ‘‘vital’’. Asked what the Soviet requirements regarding the Siralts were, Vinogradov replied thatfthe USSR” (a))must have an adequate wuarantee that the security of the Sc viet Union wilt not oe endangered, (b) that a sovereign and friendly Turkey at the Straits would not be adequate for the defense of the Straits, and (c) that Soviet use of bases In the Straits when the need arose would be essential. YUGOSLAVIA: Anti-AMG propaganda in Venezia Giulia-- Military autherities in Venezia Giulia report that Communist press attachs on the Allied Military Government are mounting, probably in an effort to obtain UNO examination of Allied actions in Venezia Giulia. The authorities also report reinforcements of Yugoslav troops in the Yugoslav zone of the province, apparently in order to apply pressure on the local population during the visit of the Council of Foreign Ministers’ Commission. FAR EAST CHINA: US moves Chinese armies--CG, Chinese Theatre reports that five Chinese armies and 18,000 service troops are being moved north by him for occupation of Manchuria. in addition to moving this force, he is supplying them with 250,000 sets of US winter clothing. Foreign Office has informed Embassy Chungking that negotiations wita rence concerning Indochina are in the final stage. Principal provisions of the proposed agreement include: (8) witndrawal of Chinese troops, (b) upnolding of prewar Chinese rights, (c) freedom of transportation on the Yunnanfndochina Railway, and elimination of duties through Haiphong. ae ',
  0.0,
  None),
 (1,
  'DAILY SUMMARY - 1946/02/16',
  'SPECIALCOLLECTION',
  None,
  'Daily Summary Collection',
  '3164644',
  None,
  None,
  None,
  datetime.datetime(2018, 8, 3, 0, 0),
  None,
  None,
  None,
  None,
  'https://www.cia.gov/readingroom/docs/DAILY%20SUMMARY%5B15423243%5D.pdf',
  'DOC_0003164644',
  'APPROVED Aor RELEASE - Historical Programs Staff DATE 15-Mar-2018 ve\n*,"\n&\nFi\ncoe eA CONFIDENTIAL (6 tab 194\ner are ee eee ee\n    \n   \nAUSPERIA; a erry OF German assets--Emoassy hi sdon reports\nthat the British Poreiem Of ies hag submitted io ihe UB sed French\nMissicns mereranda preps sing a formula ier tbe teeatmenwt vi\nGerman avsets in Anstria, with a view tu tater submission te\nthe USSR. ‘The racmorandy. propcs: tha: 1) measures alread:\ntaken apzinst Gorman assets in Austria ecusiitubs full estisfaction\nof reperation cleiras ogeinet such avsets s, &) further removals cf\nsuch asscts is reperaticns be dicentinned , and (ec) the Austrian\nGovernra tar be reaquircd to examine the titls of « “enership cf all\nGermain assets remaining in Austris and tc take such setion as\noe ae\n  \nright be required,\n   \n  \n, aha nn sche rn en o .\nITAT Vv. Rillitary TM ImITmoEnis oor id 13> coke WELL Onn Teleuteee\nwee wee oo ae -ngeerat cower\n \nAmbassador “irs peporin uae oa 14 rary General Morsan (Adie st,\nCOmmMaAnrier in wag announesd his decision to transfer ‘miiitary mao inigs, ce\nfrom Triesta to Venice as of } hpril, POP an nas inerenuy reveursad A\nHis position of 22 November; ne justifies witudrawalnow on the\ngro unds of (a) (ritisn demoiiligation and (0) the unlaciisoeot of\n*‘SOLLOUS Te Pereussious . His decidion was made over the crotest of\nUs ond Briticn vollticul reprosentatives, who are of the opinien tnat\nthe proce Jeulerte situation in Venezia Giulia will becorue ruore\n   \nMeee be.\neritical ii the next tow ronths and snould net be farther disturbed\n \nby any suggestion of Aglied railitury withdrawal from Trieste. Kins\na a . oe —T ? | a .\nrecommends that uve onuine 4d Chiefs of Stell reverse Morvan’s decision,\nand advises tiat ihe Britis representative ic maxing a similar rz-\ncommendation to the ome ffiee.\nrow Amon sador- it mbassy Lorlon nas waen informed\n \n \nBeAW: Gis vil\nit\noe ee ee ee\nd\nthat, despilé icinaide in carliacnt and las press that the British Ambassador os withdriuy fis om Madrid as Sign of displeasure, ce\nForeign Office consilers it t Ungortant that Ae remgin there until\nthe results of Den Juun’s vigit to Lisvon are known.\na\nDocument No. ( | 0.5\n“ae NO CHANGE in Cluss. []\n_ | DECLASSIFITD\n. =. Class. cu: ts s ©\na ~ DBA Hauo, 4 aoe 77\nate: oll\nLOuap 1979 7\n \n \n \n \n\x0c\nAPPROVED FOR RELEASE - Historical Programs Staff DATE 15-Mar-2018\n \n4. @8GYPT: Cabinet change--Liespite Cabinet changes ann tne intensity\n<i recent Student demonstrations, Legation Cairo rep.rts tnat local antiwritish sentiment is not as widespread or vilter as in 1919 or the\niniddle 1930’s and that any Cavinet echane will pe the result of incernal intrigues and unbalanced representaticn rather than mass\nanti-zovernment sentimert.\nFAR BAS\nne ea\njavAN: USSR requests division of Japanes2 Siinping-- Embacsy\nsfoscow reports that the Soviet Foreign Citice nas requested\nummediate transfer of one fourti of the Jazanvse naval fleet to tue\nJSSR and early division of the Japanese merenant ficet among the\nUsSsk, UK, US and China. ‘he Sovieta arg 2 that tne use of tnese\nshins tor repatriation of Japanese and other purposes connected\nwith tne Japanese surrender siioula be discussed aftr the\ndivision nas oeen effected. in connecting or the Sov-et note,\nmmbassy Moscow points oat that the Soviets are no. overating\ned 1i% Lend-Lease vessels for their own usepu eposes, and have not\nreplied to inquiries regarding Japanese shipring ceptured by them.\nin wiew of the fact that SCA nas the greatest noe? for sninping\nim implementation of the surrender, tne Embassy Suggests taat\ntia USS pe assed tc wet extent it would be villi.g to divert\nSnyiet shipping for such purposes, inthe event of a division of\ninz Japanese tlect.\n \n5. -OEA: Publicity on Ceoul Conference--Gen. ruge acdivises agamse\neeieasing & full Statement of Conference actions fc tae US or the\nLopeans. He would prefer such puvlicity “-s 5 means of pressure in\nthe tuture,’ aiter the Soviet commander as finally approved the\ncoreement.\nVHb, AMERICAS\n47. jxreection to Blue Boo. on Arveantina--US Embaesies wm Latin America\nreport that oress reacticn to tne lus Boox 1s generally favorable in\nBrazil, Chile, Columbia, euador, waraguay, Feru and Jengay. i\n“goa, aowever, were Was consideranle unfavoriole press cor ment,\ntacag ue most important paper strongly endorsed the Book.\nfmbaessy vera reports that the Peruvian Foreign Minister hac\n \n‘ gesawd whether tne Un would pive wera aconomic aid, if rejJeations wit\nve nypeeniina were severed and Argentine exports vere suut off.\nTARA \x0c\n',
  'APPROVED Aor RELEASE Historical Programs Staff DATE 15-Mar-2018 ve Fi coe eA CONFIDENTIAL (6 tab 194 er are ee eee ee AUSPERIA; a erry OF German assets--Emoassy hi sdon reports that the British Poreiem Of ies hag submitted io ihe UB sed French Missicns mereranda preps sing a formula ier tbe teeatmenwt vi German avsets in Anstria, with a view tu tater submission te the USSR. ‘The racmorandy. propcs: tha: 1) measures alread: taken apzinst Gorman assets in Austria ecusiitubs full estisfaction of reperation cleiras ogeinet such avsets s, further removals cf such asscts is reperaticns be dicentinned and (ec) the Austrian Governra tar be reaquircd to examine the titls of “enership cf all Germain assets remaining in Austris and tc take such setion as oe ae right be required, aha nn sche rn en o ITAT Vv. Rillitary TM ImITmoEnis oor id 13> coke WELL Onn Teleuteee wee wee oo ae -ngeerat cower Ambassador “irs peporin uae oa 14 rary General Morsan (Adie st, COmmMaAnrier in wag announesd his decision to transfer ‘miiitary mao inigs, ce from Triesta to Venice as of hpril, POP an nas inerenuy reveursad A His position of 22 November; ne justifies witudrawalnow on the gro unds of (a) (ritisn demoiiligation and (0) the unlaciisoeot of *‘SOLLOUS Te Pereussious His decidion was made over the crotest of Us ond Briticn vollticul reprosentatives, who are of the opinien tnat the proce Jeulerte situation in Venezia Giulia will becorue ruore Meee be. eritical ii the next tow ronths and snould net be farther disturbed by any suggestion of Aglied railitury withdrawal from Trieste. Kins a a oe —T a recommends that uve onuine 4d Chiefs of Stell reverse Morvan’s decision, and advises tiat ihe Britis representative ic maxing a similar rzcommendation to the ome ffiee. row Amon sador- it mbassy Lorlon nas waen informed BeAW: Gis vil it oe ee ee ee d that, despilé icinaide in carliacnt and las press that the British Ambassador os withdriuy fis om Madrid as Sign of displeasure, ce Foreign Office consilers it t Ungortant that Ae remgin there until the results of Den Juun’s vigit to Lisvon are known. a Document No. 0.5 “ae NO CHANGE in Cluss. _ DECLASSIFITD Class. cu: ts s a DBA Hauo, 4 aoe 77 ate: oll LOuap 1979 7 4. @8GYPT: Cabinet change--Liespite Cabinet changes ann tne intensity <i recent Student demonstrations, Legation Cairo rep.rts tnat local antiwritish sentiment is not as widespread or vilter as in 1919 or the iniddle 1930’s and that any Cavinet echane will pe the result of incernal intrigues and unbalanced representaticn rather than mass anti-zovernment sentimert. FAR BAS ne ea javAN: USSR requests division of Japanes2 Siinping-- Embacsy sfoscow reports that the Soviet Foreign Citice nas requested ummediate transfer of one fourti of the Jazanvse naval fleet to tue JSSR and early division of the Japanese merenant ficet among the UsSsk, UK, US and China. ‘he Sovieta arg 2 that tne use of tnese shins tor repatriation of Japanese and other purposes connected with tne Japanese surrender siioula be discussed aftr the division nas oeen effected. in connecting or the Sov-et note, mmbassy Moscow points oat that the Soviets are no. overating ed 1i% Lend-Lease vessels for their own usepu eposes, and have not replied to inquiries regarding Japanese shipring ceptured by them. in wiew of the fact that SCA nas the greatest noe? for sninping im implementation of the surrender, tne Embassy Suggests taat tia USS pe assed tc wet extent it would be villi.g to divert Snyiet shipping for such purposes, inthe event of a division of inz Japanese tlect. 5. -OEA: Publicity on Ceoul Conference--Gen. ruge acdivises agamse eeieasing full Statement of Conference actions fc tae US or the Lopeans. He would prefer such puvlicity “-s 5 means of pressure in the tuture,’ aiter the Soviet commander as finally approved the coreement. VHb, AMERICAS 47. jxreection to Blue Boo. on Arveantina--US Embaesies wm Latin America report that oress reacticn to tne lus Boox 1s generally favorable in Brazil, Chile, Columbia, euador, waraguay, Feru and Jengay. i “goa, aowever, were Was consideranle unfavoriole press cor ment, tacag ue most important paper strongly endorsed the Book. fmbaessy vera reports that the Peruvian Foreign Minister hac gesawd whether tne Un would pive wera aconomic aid, if rejJeations wit ve nypeeniina were severed and Argentine exports vere suut off. TARA ',
  0.0,
  None),
 (2,
  'DAILY SUMMARY - 1946/02/18',
  'SPECIALCOLLECTION',
  None,
  'Daily Summary Collection',
  '3164669',
  None,
  None,
  None,
  datetime.datetime(2018, 8, 3, 0, 0),
  None,
  None,
  None,
  None,
  'https://www.cia.gov/readingroom/docs/DAILY%20SUMMARY%5B15423249%5D.pdf',
  'DOC_0003164669',

query = "SELECT title, id, file from docs limit 10;"
with conn.cursor() as cursor:
    cursor.execute(query)
    docs = cursor.fetchall()

docs[0:10]

In [6]:
type(docs)

tuple

# Where

We can use `where` clauses to restrict the retrieval  
A `where` clause can be used with an exact match (but only a single equation is used)  
Or with a regular expression.  The `regexp` syntax is a little different: 
We specify the column first, then regexp (regular expression pattern), and finally the pattern.  
In the query below, we look for Patrice Lumumba in the _President's Daily Briefs_

In [7]:
query = """SELECT * from docs WHERE body regexp 'Lumumba' LIMIT 4;"""
with conn.cursor() as cursor:
    cursor.execute(query)
    lumumba = cursor.fetchall()

lumumba

((461,
  "THE PRESIDENT'S INTELLIGENCE REVIEW 29 AUGUST-1 SEPTEMBER 1964",
  'FOIA',
  None,
  'pdbs',
  '5959397',
  'RIPPUB',
  'T',
  15.0,
  datetime.datetime(2015, 9, 16, 0, 0),
  datetime.datetime(2015, 9, 16, 0, 0),
  None,
  None,
  datetime.datetime(2064, 9, 1, 0, 0),
  'https://www.cia.gov/library/readingroom/docs/DOC_0005959397.pdf',
  'DOC_0005959397',
  'i Declassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDP79T00936A003000200001-1\neR\nTHE PRESIDENT’S\nINTELLIGENCE REVIEW\nISSUED BY THE\nCENTRAL INTELLIGENCE AGENCY\n29 AUGUST - 1 SEPTEMBER 1964\nTOP-SEGREL\n\x0c\na — i — ie — ee ee eo\n4 Declassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDPTSTO093RA003000200001-1\n1 September 1964\n1. South Vietnam: The power struggle continues.\nKhanh appears reluctant to try to reassert his\nleadership of the government and relieve acting\nPremier Oanh, who has been talking of himself as\ndestined to lead Vietnam out of its morass.\nIn a talk with Ambassador Taylor in Dalat on\n31 August, Khanh said he might appear in Saigon in\na few days to show that he is still premier and to\nquash rumors that he is mentally ill. Taylor got\nthe impression, however, that Khanh was disinclined\nto head the government unless he had real authority.\nKhanh, however, is giving out conflicting\nstories. He has told the press he would be back\nin two wecks 50X1\n50X1\nKhiem, the 9UX1\nthird member of the Khanh-Minh-Khiem triumvirate,\nmay be maneuvering in his own behalf. General\nMinh would like to see himself as chief of state\nwith Khanh as premier.\nAlthough Khanh has some minor physical troubles,\nhe does seem to fear a Dai Vict power play. He\ntold Taylor the Military Revolutionary Council had\nasked him last week to stay on as head of government but he turned them down because of his distrust\nof the Dai Viet generals.\n(Cont\'d)\n\x0c\nC282 Fara es ea rn ea en es es ea es es oe\n—_\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA- RDP79T00936A003000200001-1\n50X1\nWe think the Communists may be biding their\ntime, hesitant to take actions which might unify\ndisputing factions in Saigon. They are probably\npreparing to move quickly, however, if the situa-\ntion stabilizes or if there is a coup. 50xX4\n2. Cyprus: The island is quiet, but the Greek\nCypriot economic blockade, despite reported agreements to end it, could push Turkish Cypriots to\nthe point of explosion if their supplies shrink\nfurther,\n50X11\n(Cont\'d)\n\x0c\nm7 £4 fF] eS Fa ea ea ea ea Ea Fe\nDeclassified in Part - Sanitized Copy Approved far Release 2015/08/04 CIA-RDP?STO0926A003000200001\nAthens has again sent Greek Defense Minister\nGaroufalias to Nicosia, reportedly to negotiate\nwith Makarios over Ankara\'s demand for permission\nto rotate part of its army contingent on Cyprus.\nThe Turks on Saturday announced temporary\npostponement of rotation, after urgent pleas from\nmany quarters.\nGaroufalias probably also hopes to learn about\nthe Makarios-Nasir talks over the weekend. Before\nhe left, Makarios told UN force commander Thimayya\nthat he would try to get an agreement to use Egyptian\nfacilities for staging aircraft. The MakariosNasir communiqué spoke obscurely of "all possible"\nEgyptian support for Cyprus.\nMakarios appears to be shifting his ground on\nthe question of union with Greece. He openly championed the idea when he was in Egypt over the weekend. He stressed, however, that the island should\nbe demilitarized, apparently with the idea of barring the present British base areas as well as any\nproposed Turkish or NATO bases.\nGeneral Grivas, in a Speech Sunday, also urged\n"unconditional enosis" without ceding Cypriot soil\nto any foreigner. Previously he was not as adamantly opposed as Makarios to a NATO base on Cyprus.\nThere is some possibility of open violence on\nthe island between Gencral Grivas\' followers and\nthe Communists; there have been recent exchanges\nof denunciation.\n(Cont\'d)\n3\nbE}\n\x0c\nGS GS Ge fo Go Be Bo ee ee ee ee! hee ee hee he\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDP79T00936A003000200001-1\nIn Turkey, demonstrators apparently intend to\ncontinue their protests against US policy, but Inonu\nhas come out against the carlier excesses and the\nsecurity forces are taking a firmer hand. The Turks\nhave not been chary with dark hints--public and\nprivate--about adopting a more independent foreign\npolicy ("\'a new way") unless Turkish demands regarding a Cyprus plan are met.\n50X11\n50X11\n\x0c\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDP79T00936A003000200001-1\n \n \n- REY MELT\n \nREPUBLIC\n  \n \n  \n \nrae\n \n  \nOF THE URANG \\\nCONGO on AGemena UELE Y rae\nI e\nMOYEN CONG? a\n" Lila eb J se ) .\n( pale dessqcritu a}\n. rd fi eh\n—_ ] Approximate Area | : “Bunio * (Mane “4\nof Uprising i Oh. Stonleyville tioBasa~., UGANDA 7\n“Ut ~ ’ \\ .\nSe ONGO Ys. sup. Po\n: mo OM ic Ue" 2 of apvu Laat ann gy.\n| WUVETTE-CENTRAIL. E a % - 4\nad ah ieeiers sIkela oo , -“ co somal\n4 he ew Labs\n«~ oy\n€ ~\n§ LEVIN dad\n_MaArN DCOMBE\nKWILU\nFOPPLOVILLE\n) x\nMULELE ®.\nRebellion :\n\\e\nan <\n  \n \n \n  \n   \n   \n   \n   \n \n    \n    \n \n \n  \n \nt\nCAMEROON _ = _ :\nPCENTRAL AFRICAN REPUBLIC ‘ SUDAN e\nwa\nOe ~ |\n|\na\n   \n  \n \n   \n  \n“+ ey axtad\nBukowy pra\n“yf\nUvira, Ria Pot\n. CER + Hea BUJUMBL RA\n\\\n    \n  \n   \n   \n \n \n\\\\\', ANGANYIRA\naértvill\n   \n \n      \n    \n   \n \n \n \n \nVe a\nyswanse. Ma ria RROIMNiIe\neee Cae Necin\na an FY a, ee\n‘ j — \\\n: 5 . ig. . MD ae eo\n‘ \\ | i rye Svat ht ™L,\nS, a 4 WHat . me\n‘ \\ eunaahad RATANGA. \\ OS\n\\ Q ; \\ =, {ORIENTAL ?} at\n| sorry \\ ‘ iv) axe\n} i folawees ““TKolwezt Jgdorville ; fee\n; Dee or KS * Ce\nam NEe | ANGOLA ge | \\ JS Elisabigthvilfe\n- Por * ’\nA a, MP\n, ar 1 femme - 6 \'\nCdn 5 t \\ :\n( | \\ A 50X11\n)} NORTHERN RHODESIA _\n4083! 3 j Deepal beanie ¢ sane Aeon int oe thiled oe ex. sheng | { eR? a\n45574 ! raps : end re ned ache ns i i a on Pree’ \' 50X1\n \n\x0c\nos\ni\nG4\nC59 fF Tors rs et OO mS\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDP79T00936A003000200001-1\nCongo: The government\'s military position is\nincreasingly precarious in the north, but has improved in the south.\nIn Katanga, Albertville has at last been recaptured--with mopping-up still going on: 50X1\nIn the north, however, the rebels hold the\ninitiative. They apparently have taken Lisala, on\nthe Congo River below Stanleyville; there is no reliable government force between Lisala and Coquilhatville, 400 miles downriver. Bunia, near Uganda,\nhas been reinforced twice in the last week, but the\ngovernment position there is reported as "grave,"\nRebels in Stanleyville now seem willing to\nlet civil aircraft land there, but the Stanleyville\nradio still threatens to hold foreign personnel\nhostage.\nOpposition and rebel leaders appear to be\ngathering in the east. Gaston Soumialot, CNL\nleader who formerly headed the rebels in Albertville, is in Stanleyville; CNL president Gbenye\nis in Bujumbura, in Burundi, and may be joined\nthere by Antoine Gizenga, the former Lumumba\nlieutenant who over the weekend announced the formation of a new "united" Lumumbist political party.\n(Cont\'d)\n—\n\x0c\n \n ——— a —— ee — ee — ee ——— ee — 2 ee —— ee — 2 ee\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDP7YTO09368A00300020000 1-1\n50X11\na\nrebel delegation was cn route to Addis Ababa for the\nOAU session on the Congo--this is scheduled for 5\nSeptember, but may be delayed to avoid conflict\nwith the Arab summit. OAU rules would deny rebels\nparticipation, but they may get backing from radical member states-~-Ghana\'s Nkrumah has been maneuvering to this end.\nTshombé\'s chances of getting a sympathetic\nAfrican hearing are being undermined by the continuing publicity about recruitment of white mercenaries.\n50X1\n50X1\n4, Communist China - North Vietnam: The Chinese\nmay be planning to strengthen their naval capability\nin the Gulf of Tonkin area,\n \n50X1\n(Cont\'d)\n\x0c\nfod\nSS SS OS) OS EO ee) ee ESS eC\neS\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDP79T00936A003000200001-1\nThis weekend, Hanoi, possibly reacting to the\nrecent deployment of a US Marine brigade in the\nSouth China Sea off Da Nang in South Vietnam. was\napparently bracing against more attacks.\n°. Communist China\n6. Laos: Informal talks in Paris among the key\nLaotian Teaders have made little apparent progress\nthus far. Formal sessions were due today.\n(Cont\'d)\nEar Thea Pracidant Only . Tan Searreat\n50X1\n50X11\n50X1\n50X1\n50X1\n\x0c\nee\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04\n<\nPremier Souvanna told Pathet Tao chief Souphannouvong that he would not insist on complete Pathet\nLao withdrawal from the Plaine des Jarres positions\noccupied earlier this year. He suggested instead\njoint control under ICC supervision. A Souphannouvong spokesman has since told the press that this\nwas rejected pending the settlement of "all outstanding problems."\nWe think the Pathet Lao would buy it only if\ngiven substantial concessions in other areas. However, in this event, strong rightists, who oppose\nany accommodation with the Pathet Lao, might rally\nsupport for the overthrow of the coalition government.\nIn Vientiane, Ambassador Unger has been worricd\nabout a lull in government military operations,\nwhich he believes only partially attributable to\nbad weather. He suspects Souvanna may have given\norders for a "stand down" during the Paris talks.\nIndonesia: There have been new demonstrations\nagainst US rubber cstates on Sumatra and against\nthe US Consulate at Medan. Local officials. however,\nseem to be adhering to orders from Djakarta to prevent damage to American properties but to "let the\npeople act against the British."\nThe USIS office in Surabayo, on Java, has\nheard that it too is to be an early target.\nThe Japanese ambassador in Djakarta, echoing\nTokyo, fully expects Japan to be next if Indoncsian\nCommunists are successful in their efforts to worsen\nUS-Indonesian relations.\n—— i —\nCIA-RDP79TO00926A002000200001-1\n=|\n\x0c\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDPF4TO093RA003000200001-1\n    \n \n    \n \n     \n    \n \n \n \n6\nTET i\nie we Sy) a ee ;\n2 AMARAN\ntuk} J\n50X1\nETHIOPIA\nFR. eral ith Mies iu\nSOM. 6408316\n \n \n \n\x0c\n——\n— a\neases a — ee See: a a ee ee ee =\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDP79T00936A003000200001-1\n——\nYemen - Saudi Arabia: The Yemeni government\'s\ncontrol in southern Yemen is threatened by a flareup of sectional and tribal rivalries triggered by\nrevolts of army elements in two important towns.\n \nShould additional troops be required to keep\nthe lid on, this could affect the current YemeniEgyptian offensive in the north aimed at rolling up\nroyalist forces before the 5 September Arab summit\nmeeting; it is already meeting stronger royulist\nresistance. Troop diversion might also be required\nto meet royalist attacks in the cast and south--the\nlatter apparently mounted from British protected\nBeihan.\nCuba\n50X1\n50X11\n50X1\n\x0c\nG53 £34 Ce CS Fes TE GD OP) Od OOS PSO\n. Declassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDP79T00936A003000200001-1\n. 50X1\n50X1\n10. Berlin: 50X1\n50X1\nthe next US helicopter 501\nto fly over East Berlin would be buzzed, forced\ndown, or shot down. We think the latter unlikely,\nbut would not be surprised by an attempt to force\none down.\nll. Ethiopia: Young officers, disgruntled over\nconditions In the services and over failure to\nsettle by force the issues with Somalia last February,\nhave been planning a coup 50X1\nWe 50X1\nthink the Emperor has probably heard about this.\nThe last coup attempt, in December 1960, failed.\n\x0c\noo oS Rs Go Go Ga Ges GS CS K-1 Co co eS\nDeclassified in Part - Sanitized Copy Approved for Release 2015/08/04 CIA-RDPTSTOOSSBA0030002\n12.\n13.\n14.\nTanganyika-Zanzibar: Tanganyikan officials\nare getting nervous about Zanzibar, over which they\nhave little or no control. Soviet military advisers\n \nChinese Communist, and possibly a few\nEast German, military advisers are — there\nHaiti: as a\nresult of recent rebel successes, there has been\na considerable increase in antigovernment plotting.\nBusiness, government, and military personnel apparently are working together on a coordinated plan\nto attack the palace and topple the Duvalier regime,\nDuvalier is diverting some troops to defend\nPort-au-Prince and can be expected to take drastic\nrepressive measures against plotting he gets wind\nof.\nChile: Observers in Santiago still give the\nedge to Christian Democrat candidate Frei over the\nCommunist-Socialist supported Allende in Friday\'s\npresidential elections. Congress names the next\npresident on 24 October. If no candidate gets a\nmajority at the polls, there would be considerable\nopportunity for Communist-Socialist manipulations,\nDONC\n01-\n1\na)\n50X1\n50X1\n50X1\n50X11\n\x0c\n \n——,\nas\nEen ee\n \n_ Declass\n—\n—\nified ir\n \n \nTOP SECRET\nUSSR: Keyhole Mission 1009, 6-13 August, disclosed a new ICBM complex in the early stages of\nconstruction near Orsk in the Ural mountains.\nThe complex has a support facility and four\nSingle silo launch areas about five miles apart.\nThe launch areas resemble those recently identified\nunder construction at Zhangiz Tobe near Semipalatinsk.\nBoth complexes, like the other 18 operational\nICBM complexes we have identified, are near main\nrail lines and aire rail served.\nWe have now identified a total of 14 single\nSilos under construction since the program began\nearly this year.\nTOP SECRET\n= St\nized Copy Approved for Release 2015/08/04 “CIA- RDP79T00936A003000200001- 1\n50X11\n \n\x0c\n',

In [8]:
query = """SELECT count(country_doc.doc_id), country_id, name, collection FROM countries INNER JOIN country_doc ON countries.id = country_doc.country_id 
INNER JOIN (SELECT id, collection FROM docs) yr ON country_doc.doc_id = yr.id GROUP by country_id, name, collection;
"""
with conn.cursor() as cursor:
    cursor.execute(query)
    country_sum = cursor.fetchall()

country_sum

((172, '032', 'Argentina', 'Daily Summary Collection'),
 (306, '040', 'Austria', 'Daily Summary Collection'),
 (68, '068', 'Bolivia', 'Daily Summary Collection'),
 (80, '076', 'Brazil', 'Daily Summary Collection'),
 (189, '100', 'Bulgaria', 'Daily Summary Collection'),
 (467, '156', 'China', 'Daily Summary Collection'),
 (27, '214', 'Dominican Republic', 'Daily Summary Collection'),
 (154, '356', 'India', 'Daily Summary Collection'),
 (305, '380', 'Italy', 'Daily Summary Collection'),
 (130, '392', 'Japan', 'Daily Summary Collection'),
 (114, '528', 'Netherlands', 'Daily Summary Collection'),
 (22, '643', 'Russia', 'Daily Summary Collection'),
 (1068, '810', 'Soviet Union', 'Daily Summary Collection'),
 (613, '826', 'United Kingdom', 'Daily Summary Collection'),
 (1341, '840', 'United States', 'Daily Summary Collection'),
 (48, '862', 'Venezuela', 'Daily Summary Collection'),
 (302,
  '890',
  'Socialist Federal Republic of Yugoslavia',
  'Daily Summary Collection'),
 (177, '200', 'Czechoslovakia', 'Daily Summary Collection'),
 (66, '208', 'Denmark', 'Daily Summary Collection'),
 (620, '250', 'France', 'Daily Summary Collection'),
 (392, '276', 'Germany', 'Daily Summary Collection'),
 (348, '300', 'Greece', 'Daily Summary Collection'),
 (220, '360', 'Indonesia', 'Daily Summary Collection'),
 (191, '616', 'Poland', 'Daily Summary Collection'),
 (193, '642', 'Romania', 'Daily Summary Collection'),
 (130, '704', 'Vietnam', 'Daily Summary Collection'),
 (75, '752', 'Sweden', 'Daily Summary Collection'),
 (49, '152', 'Chile', 'Daily Summary Collection'),
 (30, '218', 'Ecuador', 'Daily Summary Collection'),
 (127, '818', 'Egypt', 'Daily Summary Collection'),
 (270, '364', 'Iran', 'Daily Summary Collection'),
 (63, '368', 'Iraq', 'Daily Summary Collection'),
 (36, '422', 'Lebanon', 'Daily Summary Collection'),
 (43, '756', 'Switzerland', 'Daily Summary Collection'),
 (69, '760', 'Syria', 'Daily Summary Collection'),
 (120, '792', 'Turkey', 'Daily Summary Collection'),
 (3, '686', 'Senegal', 'Daily Summary Collection'),
 (74, '724', 'Spain', 'Daily Summary Collection'),
 (90, '764', 'Thailand', 'Daily Summary Collection'),
 (18, '858', 'Uruguay', 'Daily Summary Collection'),
 (15, '004', 'Afghanistan', 'Daily Summary Collection'),
 (257, '275', 'State of Palestine', 'Daily Summary Collection'),
 (136, '408', 'North Korea', 'Daily Summary Collection'),
 (144, '410', 'South Korea', 'Daily Summary Collection'),
 (167, '348', 'Hungary', 'Daily Summary Collection'),
 (18, '418', 'Laos', 'Daily Summary Collection'),
 (22, '504', 'Morocco', 'Daily Summary Collection'),
 (85, '031', 'Azerbaijan', 'Daily Summary Collection'),
 (57, '788', 'Tunisia', 'Daily Summary Collection'),
 (18, '231', 'Ethiopia', 'Daily Summary Collection'),
 (86, '280', 'West Germany', 'Daily Summary Collection'),
 (474, '214', 'Dominican Republic', 'pdbs'),
 (258, '284', 'West Berlin', 'pdbs'),
 (423, '591', 'Panama', 'pdbs'),
 (672, '792', 'Turkey', 'pdbs'),
 (285, '458', 'Malaysia', 'pdbs'),
 (360, '404', 'Kenya', 'pdbs'),
 (1013, '764', 'Thailand', 'pdbs'),
 (2161, '156', 'China', 'pdbs'),
 (3616, '840', 'United States', 'pdbs'),
 (506, '076', 'Brazil', 'pdbs'),
 (168, '834', 'Tanzania', 'pdbs'),
 (223, '716', 'Zimbabwe', 'pdbs'),
 (1430, '250', 'France', 'pdbs'),
 (222, '566', 'Nigeria', 'pdbs'),
 (87, '756', 'Switzerland', 'pdbs'),
 (2415, '714', 'South Vietnam', 'pdbs'),
 (410, '410', 'South Korea', 'pdbs'),
 (430, '200', 'Czechoslovakia', 'pdbs'),
 (3956, '810', 'Soviet Union', 'pdbs'),
 (759, '400', 'Jordan', 'pdbs'),
 (1676, '418', 'Laos', 'pdbs'),
 (383, '616', 'Poland', 'pdbs'),
 (384, '788', 'Tunisia', 'pdbs'),
 (727, '360', 'Indonesia', 'pdbs'),
 (220, '158', 'Taiwan', 'pdbs'),
 (93, '275', 'State of Palestine', 'pdbs'),
 (607, '278', 'East Germany', 'pdbs'),
 (121, '282', 'East Berlin', 'pdbs'),
 (419, '620', 'Portugal', 'pdbs'),
 (1276, '116', 'Cambodia', 'pdbs'),
 (265, '608', 'Philippines', 'pdbs'),
 (1004, '280', 'West Germany', 'pdbs'),
 (459, '152', 'Chile', 'pdbs'),
 (335, '862', 'Venezuela', 'pdbs'),
 (1534, '818', 'Egypt', 'pdbs'),
 (484, '012', 'Algeria', 'pdbs'),
 (311, '056', 'Belgium', 'pdbs'),
 (197, '320', 'Guatemala', 'pdbs'),
 (571, '392', 'Japan', 'pdbs'),
 (246, '104', 'Myanmar', 'pdbs'),
 (595, '276', 'Germany', 'pdbs'),
 (1016, '760', 'Syria', 'pdbs'),
 (754, '422', 'Lebanon', 'pdbs'),
 (192, '036', 'Australia', 'pdbs'),
 (61, '104', 'Myanmar', 'Daily Summary Collection'),
 (131, '056', 'Belgium', 'Daily Summary Collection'),
 (52, '170', 'Colombia', 'Daily Summary Collection'),
 (171, '324', 'Guinea', 'pdbs'),
 (482, '434', 'Libya', 'pdbs'),
 (1144, '376', 'Israel', 'pdbs'),
 (538, '180', 'Democratic Republic of the Congo', 'pdbs'),
 (293, '408', 'North Korea', 'pdbs'),
 (1238, '192', 'Cuba', 'pdbs'),
 (183, '710', 'South Africa', 'pdbs'),
 (2065, '704', 'Vietnam', 'pdbs'),
 (777, '826', 'United Kingdom', 'pdbs'),
 (641, '356', 'India', 'pdbs'),
 (42, '646', 'Rwanda', 'pdbs'),
 (743, '196', 'Cyprus', 'pdbs'),
 (580, '682', 'Saudi Arabia', 'pdbs'),
 (507, '368', 'Iraq', 'pdbs'),
 (6, '780', 'Trinidad and Tobago', 'pdbs'),
 (322, '024', 'Angola', 'pdbs'),
 (277, '586', 'Pakistan', 'pdbs'),
 (27, '028', 'Antigua and Barbuda', 'pdbs'),
 (38, '328', 'Guyana', 'pdbs'),
 (60, '340', 'Honduras', 'pdbs'),
 (128, '706', 'Somalia', 'pdbs'),
 (386, '068', 'Bolivia', 'pdbs'),
 (212, '890', 'Socialist Federal Republic of Yugoslavia', 'pdbs'),
 (171, '288', 'Ghana', 'pdbs'),
 (157, '332', 'Haiti', 'pdbs'),
 (73, '108', 'Burundi', 'pdbs'),
 (33, '388', 'Jamaica', 'pdbs'),
 (301, '642', 'Romania', 'pdbs'),
 (277, '178', 'Republic of the Congo', 'pdbs'),
 (90, '208', 'Denmark', 'pdbs'),
 (178, '348', 'Hungary', 'pdbs'),
 (313, '380', 'Italy', 'pdbs'),
 (142, '170', 'Colombia', 'pdbs'),
 (205, '050', 'Bangladesh', 'pdbs'),
 (75, '886', 'North Yemen', 'pdbs'),
 (491, '218', 'Ecuador', 'pdbs'),
 (332, '364', 'Iran', 'pdbs'),
 (194, '124', 'Canada', 'pdbs'),
 (159, '414', 'Kuwait', 'pdbs'),
 (218, '504', 'Morocco', 'pdbs'),
 (304, '231', 'Ethiopia', 'pdbs'),
 (747, '418', 'Laos', 'Current/Central Intelligence Bulletin Collection'),
 (577,
  '714',
  'South Vietnam',
  'Current/Central Intelligence Bulletin Collection'),
 (850, '364', 'Iran', 'Current/Central Intelligence Bulletin Collection'),
 (2849,
  '810',
  'Soviet Union',
  'Current/Central Intelligence Bulletin Collection'),
 (804,
  '278',
  'East Germany',
  'Current/Central Intelligence Bulletin Collection'),
 (199, '100', 'Bulgaria', 'Current/Central Intelligence Bulletin Collection'),
 (860, '356', 'India', 'Current/Central Intelligence Bulletin Collection'),
 (940, '368', 'Iraq', 'Current/Central Intelligence Bulletin Collection'),
 (1051,
  '280',
  'West Germany',
  'Current/Central Intelligence Bulletin Collection'),
 (139, '152', 'Chile', 'Current/Central Intelligence Bulletin Collection'),
 (156, '858', 'Uruguay', 'pdbs'),
 (36, '254', 'French Guiana', 'pdbs'),
 (658, '300', 'Greece', 'pdbs'),
 (106, '528', 'Netherlands', 'pdbs'),
 (2595,
  '840',
  'United States',
  'Current/Central Intelligence Bulletin Collection'),
 (93, '246', 'Finland', 'pdbs'),
 (194, '724', 'Spain', 'pdbs'),
 (72, '496', 'Mongolia', 'pdbs'),
 (120, '702', 'Singapore', 'pdbs'),
 (190, '729', 'Sudan', 'pdbs'),
 (274,
  '178',
  'Republic of the Congo',
  'Current/Central Intelligence Bulletin Collection'),
 (526, '788', 'Tunisia', 'Current/Central Intelligence Bulletin Collection'),
 (899, '376', 'Israel', 'Current/Central Intelligence Bulletin Collection'),
 (622,
  '890',
  'Socialist Federal Republic of Yugoslavia',
  'Current/Central Intelligence Bulletin Collection'),
 (195, '288', 'Ghana', 'Current/Central Intelligence Bulletin Collection'),
 (1673, '156', 'China', 'Current/Central Intelligence Bulletin Collection'),
 (1501,
  '826',
  'United Kingdom',
  'Current/Central Intelligence Bulletin Collection'),
 (128, '724', 'Spain', 'Current/Central Intelligence Bulletin Collection'),
 (1712, '818', 'Egypt', 'Current/Central Intelligence Bulletin Collection'),
 (408, '380', 'Italy', 'Current/Central Intelligence Bulletin Collection'),
 (875, '360', 'Indonesia', 'Current/Central Intelligence Bulletin Collection'),
 (284,
  '284',
  'West Berlin',
  'Current/Central Intelligence Bulletin Collection'),
 (226, '729', 'Sudan', 'Current/Central Intelligence Bulletin Collection'),
 (1670, '250', 'France', 'Current/Central Intelligence Bulletin Collection'),
 (645, '158', 'Taiwan', 'Current/Central Intelligence Bulletin Collection'),
 (934, '760', 'Syria', 'Current/Central Intelligence Bulletin Collection'),
 (791, '704', 'Vietnam', 'Current/Central Intelligence Bulletin Collection'),
 (233, '887', 'Yemen', 'Current/Central Intelligence Bulletin Collection'),
 (99, '558', 'Nicaragua', 'Current/Central Intelligence Bulletin Collection'),
 (188, '320', 'Guatemala', 'Current/Central Intelligence Bulletin Collection'),
 (78, '332', 'Haiti', 'Current/Central Intelligence Bulletin Collection'),
 (254, '862', 'Venezuela', 'Current/Central Intelligence Bulletin Collection'),
 (326, '056', 'Belgium', 'Current/Central Intelligence Bulletin Collection'),
 (715, '616', 'Poland', 'Current/Central Intelligence Bulletin Collection'),
 (411, '192', 'Cuba', 'Current/Central Intelligence Bulletin Collection'),
 (535,
  '682',
  'Saudi Arabia',
  'Current/Central Intelligence Bulletin Collection'),
 (92, '586', 'Pakistan', 'Current/Central Intelligence Bulletin Collection'),
 (125, '702', 'Singapore', 'Current/Central Intelligence Bulletin Collection'),
 (231,
  '608',
  'Philippines',
  'Current/Central Intelligence Bulletin Collection'),
 (736, '400', 'Jordan', 'Current/Central Intelligence Bulletin Collection'),
 (458, '422', 'Lebanon', 'Current/Central Intelligence Bulletin Collection'),
 (5, '440', 'Lithuania', 'Current/Central Intelligence Bulletin Collection'),
 (695, '276', 'Germany', 'Current/Central Intelligence Bulletin Collection'),
 (458, '504', 'Morocco', 'Current/Central Intelligence Bulletin Collection'),
 (117,
  '214',
  'Dominican Republic',
  'Current/Central Intelligence Bulletin Collection'),
 (526, '300', 'Greece', 'Current/Central Intelligence Bulletin Collection'),
 (352,
  '408',
  'North Korea',
  'Current/Central Intelligence Bulletin Collection'),
 (188, '076', 'Brazil', 'Current/Central Intelligence Bulletin Collection'),
 (135, '620', 'Portugal', 'Current/Central Intelligence Bulletin Collection'),
 (422, '348', 'Hungary', 'Current/Central Intelligence Bulletin Collection'),
 (16, '634', 'Qatar', 'Current/Central Intelligence Bulletin Collection'),
 (187, '344', 'Hong Kong', 'Current/Central Intelligence Bulletin Collection'),
 (113, '036', 'Australia', 'Current/Central Intelligence Bulletin Collection'),
 (586,
  '200',
  'Czechoslovakia',
  'Current/Central Intelligence Bulletin Collection'),
 (712, '104', 'Myanmar', 'Current/Central Intelligence Bulletin Collection'),
 (21, '060', 'Bermuda', 'Current/Central Intelligence Bulletin Collection'),
 (718, '392', 'Japan', 'Current/Central Intelligence Bulletin Collection'),
 (362, '116', 'Cambodia', 'Current/Central Intelligence Bulletin Collection'),
 (266, '434', 'Libya', 'Current/Central Intelligence Bulletin Collection'),
 (678, '792', 'Turkey', 'Current/Central Intelligence Bulletin Collection'),
 (477, '764', 'Thailand', 'Current/Central Intelligence Bulletin Collection'),
 (57, '024', 'Angola', 'Current/Central Intelligence Bulletin Collection'),
 (186, '324', 'Guinea', 'Current/Central Intelligence Bulletin Collection'),
 (5, '096', 'Brunei', 'Current/Central Intelligence Bulletin Collection'),
 (293,
  '004',
  'Afghanistan',
  'Current/Central Intelligence Bulletin Collection'),
 (195, '752', 'Sweden', 'Current/Central Intelligence Bulletin Collection'),
 (28, '232', 'Eritrea', 'Current/Central Intelligence Bulletin Collection'),
 (269, '642', 'Romania', 'Current/Central Intelligence Bulletin Collection'),
 (166,
  '528',
  'Netherlands',
  'Current/Central Intelligence Bulletin Collection'),
 (116, '208', 'Denmark', 'Current/Central Intelligence Bulletin Collection'),
 (284, '032', 'Argentina', 'Current/Central Intelligence Bulletin Collection'),
 (91, '218', 'Ecuador', 'Current/Central Intelligence Bulletin Collection'),
 (133, '484', 'Mexico', 'Current/Central Intelligence Bulletin Collection'),
 (338, '196', 'Cyprus', 'Current/Central Intelligence Bulletin Collection'),
 (14, '388', 'Jamaica', 'Current/Central Intelligence Bulletin Collection'),
 (77, '566', 'Nigeria', 'Current/Central Intelligence Bulletin Collection'),
 (93, '524', 'Nepal', 'Current/Central Intelligence Bulletin Collection'),
 (377, '040', 'Austria', 'Current/Central Intelligence Bulletin Collection'),
 (4, '480', 'Mauritius', 'Current/Central Intelligence Bulletin Collection'),
 (41,
  '554',
  'New Zealand',
  'Current/Central Intelligence Bulletin Collection'),
 (459,
  '410',
  'South Korea',
  'Current/Central Intelligence Bulletin Collection'),
 (108,
  '275',
  'State of Palestine',
  'Current/Central Intelligence Bulletin Collection'),
 (47, '604', 'Peru', 'Daily Summary Collection'),
 (51, '352', 'Iceland', 'Daily Summary Collection'),
 (53, '714', 'South Vietnam', 'Daily Summary Collection'),
 (5, '710', 'South Africa', 'Daily Summary Collection'),
 (122, '376', 'Israel', 'Daily Summary Collection'),
 (12, '304', 'Greenland', 'Daily Summary Collection'),
 (16, '188', 'Costa Rica', 'Daily Summary Collection'),
 (50, '608', 'Philippines', 'Daily Summary Collection'),
 (46, '278', 'East Germany', 'Daily Summary Collection'),
 (244, '604', 'Peru', 'pdbs'),
 (153, '100', 'Bulgaria', 'pdbs'),
 (251, '484', 'Mexico', 'pdbs'),
 (82, '232', 'Eritrea', 'pdbs'),
 (102, '720', 'South Yemen', 'pdbs'),
 (32, '516', 'Namibia', 'pdbs'),
 (13, '586', 'Pakistan', 'Daily Summary Collection'),
 (32, '344', 'Hong Kong', 'Daily Summary Collection'),
 (63, '140', 'Central African Republic', 'pdbs'),
 (127, '266', 'Gabon', 'pdbs'),
 (106, '800', 'Uganda', 'pdbs'),
 (401, '032', 'Argentina', 'pdbs'),
 (160, '752', 'Sweden', 'pdbs'),
 (38, '558', 'Nicaragua', 'pdbs'),
 (38, '804', 'Ukraine', 'pdbs'),
 (138, '040', 'Austria', 'pdbs'),
 (22, '630', 'Puerto Rico', 'pdbs'),
 (402, '887', 'Yemen', 'pdbs'),
 (32, '784', 'United Arab Emirates', 'pdbs'),
 (161, '894', 'Zambia', 'pdbs'),
 (116, '344', 'Hong Kong', 'pdbs'),
 (39, '554', 'New Zealand', 'pdbs'),
 (56, '578', 'Norway', 'pdbs'),
 (16, '800', 'Uganda', 'Current/Central Intelligence Bulletin Collection'),
 (83, '470', 'Malta', 'pdbs'),
 (16, '144', 'Sri Lanka', 'pdbs'),
 (24, '048', 'Bahrain', 'pdbs'),
 (44, '188', 'Costa Rica', 'pdbs'),
 (91, '858', 'Uruguay', 'Current/Central Intelligence Bulletin Collection'),
 (130, '068', 'Bolivia', 'Current/Central Intelligence Bulletin Collection'),
 (295,
  '180',
  'Democratic Republic of the Congo',
  'Current/Central Intelligence Bulletin Collection'),
 (9, '266', 'Gabon', 'Current/Central Intelligence Bulletin Collection'),
 (151, '404', 'Kenya', 'Current/Central Intelligence Bulletin Collection'),
 (63, '466', 'Mali', 'Current/Central Intelligence Bulletin Collection'),
 (27, '446', 'Macau', 'Current/Central Intelligence Bulletin Collection'),
 (74, '352', 'Iceland', 'Current/Central Intelligence Bulletin Collection'),
 (509, '012', 'Algeria', 'Current/Central Intelligence Bulletin Collection'),
 (76, '144', 'Sri Lanka', 'Current/Central Intelligence Bulletin Collection'),
 (79,
  '720',
  'South Yemen',
  'Current/Central Intelligence Bulletin Collection'),
 (28, '716', 'Zimbabwe', 'Current/Central Intelligence Bulletin Collection'),
 (9, '112', 'Belarus', 'Current/Central Intelligence Bulletin Collection'),
 (143,
  '756',
  'Switzerland',
  'Current/Central Intelligence Bulletin Collection'),
 (115, '895', 'Tibet', 'Current/Central Intelligence Bulletin Collection'),
 (145,
  '282',
  'East Berlin',
  'Current/Central Intelligence Bulletin Collection'),
 (84, '188', 'Costa Rica', 'Current/Central Intelligence Bulletin Collection'),
 (54, '036', 'Australia', 'Daily Summary Collection'),
 (31, '682', 'Saudi Arabia', 'Daily Summary Collection'),
 (6, '196', 'Cyprus', 'Daily Summary Collection'),
 (48, '591', 'Panama', 'Daily Summary Collection'),
 (28, '558', 'Nicaragua', 'Daily Summary Collection'),
 (23, '434', 'Libya', 'Daily Summary Collection'),
 (56, '352', 'Iceland', 'pdbs'),
 (4, '191', 'Croatia', 'Daily Summary Collection'),
 (84, '008', 'Albania', 'pdbs'),
 (35, '222', 'El Salvador', 'pdbs'),
 (95, '004', 'Afghanistan', 'pdbs'),
 (27, '064', 'Bhutan', 'pdbs'),
 (44, '120', 'Cameroon', 'pdbs'),
 (18, '384', "CA'te d'Ivoire", 'pdbs'),
 (10, '274', 'Gaza Strip', 'pdbs'),
 (24, '512', 'Oman', 'pdbs'),
 (105, '414', 'Kuwait', 'Current/Central Intelligence Bulletin Collection'),
 (89, '578', 'Norway', 'Current/Central Intelligence Bulletin Collection'),
 (21, '478', 'Mauritania', 'Current/Central Intelligence Bulletin Collection'),
 (41, '600', 'Paraguay', 'Current/Central Intelligence Bulletin Collection'),
 (12,
  '438',
  'Liechtenstein',
  'Current/Central Intelligence Bulletin Collection'),
 (9, '050', 'Bangladesh', 'Current/Central Intelligence Bulletin Collection'),
 (88, '124', 'Canada', 'Current/Central Intelligence Bulletin Collection'),
 (135, '008', 'Albania', 'Current/Central Intelligence Bulletin Collection'),
 (49,
  '222',
  'El Salvador',
  'Current/Central Intelligence Bulletin Collection'),
 (78, '246', 'Finland', 'Current/Central Intelligence Bulletin Collection'),
 (26,
  '650',
  'Ryukyu Islands',
  'Current/Central Intelligence Bulletin Collection'),
 (29, '064', 'Bhutan', 'Current/Central Intelligence Bulletin Collection'),
 (16, '470', 'Malta', 'Current/Central Intelligence Bulletin Collection'),
 (151, '231', 'Ethiopia', 'Current/Central Intelligence Bulletin Collection'),
 (90, '340', 'Honduras', 'Current/Central Intelligence Bulletin Collection'),
 (93, '170', 'Colombia', 'Current/Central Intelligence Bulletin Collection'),
 (20,
  '268',
  'Georgia (country)',
  'Current/Central Intelligence Bulletin Collection'),
 (88,
  '710',
  'South Africa',
  'Current/Central Intelligence Bulletin Collection'),
 (3,
  '162',
  'Christmas Island',
  'Current/Central Intelligence Bulletin Collection'),
 (33, '804', 'Ukraine', 'Current/Central Intelligence Bulletin Collection'),
 (47,
  '594',
  'Panama Canal Zone',
  'Current/Central Intelligence Bulletin Collection'),
 (9, '012', 'Algeria', 'Daily Summary Collection'),
 (48, '620', 'Portugal', 'Daily Summary Collection'),
 (51, '600', 'Paraguay', 'Daily Summary Collection'),
 (17, '232', 'Eritrea', 'Daily Summary Collection'),
 (41, '400', 'Jordan', 'Daily Summary Collection'),
 (6, '442', 'Luxembourg', 'Daily Summary Collection'),
 (31, '562', 'Niger', 'pdbs'),
 (40, '478', 'Mauritania', 'pdbs'),
 (28, '600', 'Paraguay', 'pdbs'),
 (11, '044', 'The Bahamas', 'pdbs'),
 (2, '212', 'Dominica', 'pdbs'),
 (39, '524', 'Nepal', 'pdbs'),
 (32, '072', 'Botswana', 'pdbs'),
 (39, '706', 'Somalia', 'Current/Central Intelligence Bulletin Collection'),
 (72, '643', 'Russia', 'Current/Central Intelligence Bulletin Collection'),
 (110, '591', 'Panama', 'Current/Central Intelligence Bulletin Collection'),
 (63, '604', 'Peru', 'Current/Central Intelligence Bulletin Collection'),
 (8, '262', 'Djibouti', 'Current/Central Intelligence Bulletin Collection'),
 (34, '442', 'Luxembourg', 'Current/Central Intelligence Bulletin Collection'),
 (3, '234', 'Faroe Islands', 'Daily Summary Collection'),
 (2, '140', 'Central African Republic', 'Daily Summary Collection'),
 (6, '132', 'Cabo Verde', 'pdbs'),
 (76, '158', 'Taiwan', 'Daily Summary Collection'),
 (10, '895', 'Tibet', 'Daily Summary Collection'),
 (46, '594', 'Panama Canal Zone', 'pdbs'),
 (14, '060', 'Bermuda', 'pdbs'),
 (4, '450', 'Madagascar', 'pdbs'),
 (86, '508', 'Mozambique', 'pdbs'),
 (11, '304', 'Greenland', 'pdbs'),
 (36, '686', 'Senegal', 'pdbs'),
 (11,
  '372',
  'Republic of Ireland',
  'Current/Central Intelligence Bulletin Collection'),
 (8,
  '784',

In [9]:
query = """SELECT count(country_doc.doc_id), country_id, name, collection FROM countries INNER JOIN country_doc ON countries.id = country_doc.country_id 
INNER JOIN (SELECT id, collection FROM docs) yr ON country_doc.doc_id = yr.id GROUP by country_id, name, collection ORDER BY count(country_doc.doc_id) LIMIT 20;
"""
with conn.cursor() as cursor:
    cursor.execute(query)
    country_sum = cursor.fetchall()

country_sum

((1, '044', 'The Bahamas', 'Current/Central Intelligence Bulletin Collection'),
 (1, '498', 'Moldova', 'Daily Summary Collection'),
 (1,
  '540',
  'New Caledonia',
  'Current/Central Intelligence Bulletin Collection'),
 (1, '533', 'Aruba', 'Daily Summary Collection'),
 (1, '650', 'Ryukyu Islands', 'pdbs'),
 (1, '748', 'Swaziland', 'Current/Central Intelligence Bulletin Collection'),
 (1, '398', 'Kazakhstan', 'Daily Summary Collection'),
 (1, '282', 'East Berlin', 'Daily Summary Collection'),
 (1, '530', 'Netherlands Antilles', 'pdbs'),
 (1, '028', 'Antigua and Barbuda', 'Daily Summary Collection'),
 (1, '454', 'Malawi', 'Current/Central Intelligence Bulletin Collection'),
 (1, '180', 'Democratic Republic of the Congo', 'Daily Summary Collection'),
 (1,
  '582',
  'Trust Territory of the Pacific Islands',
  'Current/Central Intelligence Bulletin Collection'),
 (1, '784', 'United Arab Emirates', 'Daily Summary Collection'),
 (1, '440', 'Lithuania', 'Daily Summary Collection'),
 (1, '020', 'Andorra', 'Current/Central Intelligence Bulletin Collection'),
 (1, '548', 'Vanuatu', 'pdbs'),
 (1, '470', 'Malta', 'Daily Summary Collection'),
 (1, '316', 'Guam', 'Current/Central Intelligence Bulletin Collection'),
 (1, '070', 'Bosnia and Herzegovina', 'pdbs'))

In [10]:
query = """SELECT count(country_doc.doc_id), country_id, name, collection FROM countries INNER JOIN country_doc ON countries.id = country_doc.country_id 
INNER JOIN (SELECT id, collection FROM docs) yr ON country_doc.doc_id = yr.id GROUP by country_id, name, collection ORDER BY count(country_doc.doc_id) DESC LIMIT 20;
"""
with conn.cursor() as cursor:
    cursor.execute(query)
    country_sum = cursor.fetchall()

country_sum

((3956, '810', 'Soviet Union', 'pdbs'),
 (3616, '840', 'United States', 'pdbs'),
 (2849,
  '810',
  'Soviet Union',
  'Current/Central Intelligence Bulletin Collection'),
 (2595,
  '840',
  'United States',
  'Current/Central Intelligence Bulletin Collection'),
 (2415, '714', 'South Vietnam', 'pdbs'),
 (2161, '156', 'China', 'pdbs'),
 (2065, '704', 'Vietnam', 'pdbs'),
 (1712, '818', 'Egypt', 'Current/Central Intelligence Bulletin Collection'),
 (1676, '418', 'Laos', 'pdbs'),
 (1673, '156', 'China', 'Current/Central Intelligence Bulletin Collection'),
 (1670, '250', 'France', 'Current/Central Intelligence Bulletin Collection'),
 (1534, '818', 'Egypt', 'pdbs'),
 (1501,
  '826',
  'United Kingdom',
  'Current/Central Intelligence Bulletin Collection'),
 (1430, '250', 'France', 'pdbs'),
 (1341, '840', 'United States', 'Daily Summary Collection'),
 (1276, '116', 'Cambodia', 'pdbs'),
 (1238, '192', 'Cuba', 'pdbs'),
 (1144, '376', 'Israel', 'pdbs'),
 (1068, '810', 'Soviet Union', 'Daily Summary Collection'),
 (1051,
  '280',
  'West Germany',
  'Current/Central Intelligence Bulletin Collection'))

# Pandas 

We can also bring SQL tables directly into Pandas  

`pymysql` does not work well with pandas  
Instead we have to use `sqlalchemy` to connect to the database  
The terminology differs but the concept is the same  

First, we need to set up a connection to the database  
Unlike `pymysql` `sqlalchemy` calls the connection an engine  

## pymysql
```
conn = pymysql.connect(
    host=localhost, user=GR5072, password=GR_5072, db='declassification_pdbs'
)
```

## sqlengine

engine = create_engine("mysql+pymysql://GR5072:GR_5072@localhost/declassification_pdbs")

In [11]:
from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session

engine = create_engine("mysql+pymysql://GR5072:GR_5072@localhost/declassification_pdbs")
with Session(engine) as session: 
    df=pd.read_sql('docs', con=engine)
    session.close()

In [12]:
# read_sql
?pd.read_sql

Signature:
pd.read_sql(
    sql,
    con,
    index_col: 'str | list[str] | None' = None,
    coerce_float: 'bool' = True,
    params=None,
    parse_dates=None,
    columns: 'list[str] | None' = None,
    chunksize: 'int | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
    dtype: 'DtypeArg | None' = None,
) -> 'DataFrame | Iterator[DataFrame]'
Docstring:
Read SQL query or database table into a DataFrame.

This function is a convenience wrapper around ``read_sql_table`` and
``read_sql_query`` (for backward compatibility). It will delegate
to the specific function depending on the provided input. A SQL query
will be routed to ``read_sql_query``, while a database table name will
be routed to ``read_sql_table``. Note that the delegated function might
have more specific notes about their functionality not listed here.

Parameters
----------
sql : str or SQLAlchemy Selectable (select or text object)
    SQL query to be executed or a table name.
con : ADBC Connection, SQLAlchemy connectable, str, or sqlite3 connection
    ADBC provides high performance I/O with native type support, where available.
    Using SQLAlchemy makes it possible to use any DB supported by that
    library. If a DBAPI2 object, only sqlite3 is supported. The user is responsible
    for engine disposal and connection closure for the ADBC connection and
    SQLAlchemy connectable; str connections are closed automatically. See
    `here <https://docs.sqlalchemy.org/en/20/core/connections.html>`_.
index_col : str or list of str, optional, default: None
    Column(s) to set as index(MultiIndex).
coerce_float : bool, default True
    Attempts to convert values of non-string, non-numeric objects (like
    decimal.Decimal) to floating point, useful for SQL result sets.
params : list, tuple or dict, optional, default: None
    List of parameters to pass to execute method.  The syntax used
    to pass parameters is database driver dependent. Check your
    database driver documentation for which of the five syntax styles,
    described in PEP 249's paramstyle, is supported.
    Eg. for psycopg2, uses %(name)s so use params={'name' : 'value'}.
parse_dates : list or dict, default: None
    - List of column names to parse as dates.
    - Dict of ``{column_name: format string}`` where format string is
      strftime compatible in case of parsing string times, or is one of
      (D, s, ns, ms, us) in case of parsing integer timestamps.
    - Dict of ``{column_name: arg dict}``, where the arg dict corresponds
      to the keyword arguments of :func:`pandas.to_datetime`
      Especially useful with databases without native Datetime support,
      such as SQLite.
columns : list, default: None
    List of column names to select from SQL table (only used when reading
    a table).
chunksize : int, default None
    If specified, return an iterator where `chunksize` is the
    number of rows to include in each chunk.
dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). Behaviour is as follows:

    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
      (default).
    * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
      DataFrame.

    .. versionadded:: 2.0
dtype : Type name or dict of columns
    Data type for data or columns. E.g. np.float64 or
    {'a': np.float64, 'b': np.int32, 'c': 'Int64'}.
    The argument is ignored if a table is passed instead of a query.

    .. versionadded:: 2.0.0

Returns
-------
DataFrame or Iterator[DataFrame]

See Also
--------
read_sql_table : Read SQL database table into a DataFrame.
read_sql_query : Read SQL query into a DataFrame.

Examples
--------
Read data from SQL via either a SQL query or a SQL tablename.
When using a SQLite database only SQL queries are accepted,
providing only the SQL tablename will result in an error.

>>> from sqlite3 import connect
>>> conn = connect(':memory:')
>>> df = pd.DataFrame(data=[[0, '10/11/12'], [1, '12/11/10']],
...                   columns=['int_column', 'date_column'])
>>> df.to_sql(name='test_data', con=conn)
2

>>> pd.read_sql('SELECT int_column, date_column FROM test_data', conn)
   int_column date_column
0           0    10/11/12
1           1    12/11/10

>>> pd.read_sql('test_data', 'postgres:///db_name')  # doctest:+SKIP

Apply date parsing to columns through the ``parse_dates`` argument
The ``parse_dates`` argument calls ``pd.to_datetime`` on the provided columns.
Custom argument values for applying ``pd.to_datetime`` on a column are specified
via a dictionary format:

>>> pd.read_sql('SELECT int_column, date_column FROM test_data',
...             conn,
...             parse_dates={"date_column": {"format": "%d/%m/%y"}})
   int_column date_column
0           0  2012-11-10
1           1  2010-11-12

.. versionadded:: 2.2.0

   pandas now supports reading via ADBC drivers

>>> from adbc_driver_postgresql import dbapi  # doctest:+SKIP
>>> with dbapi.connect('postgres:///db_name') as conn:  # doctest:+SKIP
...     pd.read_sql('SELECT int_column FROM test_data', conn)
   int_column
0           0
1           1
File:      c:\users\arpie\anaconda3\lib\site-packages\pandas\io\sql.py
Type:      function

# read_sql

In [13]:
df.head()

,index,title,doctype,keywords,collection,docno,release_decis,origclass,pages,doccreation,docrelease,sequenceno,caseno,pubdate,file,id,raw_body,body,redactcode_no,collecttype
0,0,DAILY SUMMARY - 1946/02/15,SPECIALCOLLECTION,None,Daily Summary Collection,3164645,None,None,NaN,2018-08-03,NaT,NaN,NaN,NaT,https://www.cia.gov/readingroom/docs/DAILY%20S...,DOC_0003164645,APPROVED FOR RELEASE - Historical Programs Sta...,Historical Programs Staff15 March 2018 5 CN s...,0.0,None
1,1,DAILY SUMMARY - 1946/02/16,SPECIALCOLLECTION,None,Daily Summary Collection,3164644,None,None,NaN,2018-08-03,NaT,NaN,NaN,NaT,https://www.cia.gov/readingroom/docs/DAILY%20S...,DOC_0003164644,APPROVED Aor RELEASE - Historical Programs Sta...,APPROVED Aor RELEASE Historical Programs Staff...,0.0,None
2,2,DAILY SUMMARY - 1946/02/18,SPECIALCOLLECTION,None,Daily Summary Collection,3164669,None,None,NaN,2018-08-03,NaT,NaN,NaN,NaT,https://www.cia.gov/readingroom/docs/DAILY%20S...,DOC_0003164669,a st\nAPPROVED FOR RELEASE - Historical Progra...,a stm1} vvVittiv io 2 CTA LL Te (PLE EUROPE l....,0.0,None
3,3,DAILY SUMMARY - 1946/02/19,SPECIALCOLLECTION,None,Daily Summary Collection,3164668,None,None,NaN,2018-08-03,NaT,NaN,NaN,NaT,https://www.cia.gov/readingroom/docs/DAILY%20S...,DOC_0003164668,APPROVED FOR RELEASE - Historical Programs Sta...,Historical Programs Staff DATE 15-Mar-2018 ff...,0.0,None
4,4,DAILY SUMMARY - 1946/02/20,SPECIALCOLLECTION,None,Daily Summary Collection,3164667,None,None,NaN,2018-08-03,NaT,NaN,NaN,NaT,https://www.cia.gov/readingroom/docs/DAILY%20S...,DOC_0003164667,APPROVED FOR RELEASE - Historical Programs Sta...,Historical Programs Staff DATE 15-Mar-2018 C)...,0.0,None

In [14]:
query = """SELECT * from docs WHERE body regexp 'Lumumba';"""
engine = create_engine("mysql+pymysql://GR5072:GR_5072@localhost/declassification_pdbs")
with Session(engine) as session: 
    df=pd.read_sql(query, con=engine)
    session.close()
df.head()

,index,title,doctype,keywords,collection,docno,release_decis,origclass,pages,doccreation,docrelease,sequenceno,caseno,pubdate,file,id,raw_body,body,redactcode_no,collecttype
0,461,THE PRESIDENT'S INTELLIGENCE REVIEW 29 AUGUST-...,FOIA,None,pdbs,5959397,RIPPUB,T,15.0,2015-09-16,2015-09-16,None,None,2064-09-01,https://www.cia.gov/library/readingroom/docs/D...,DOC_0005959397,i Declassified in Part - Sanitized Copy Approv...,i Declassified in Part Sanitized Copy Approved...,33.0,President's Daily Brief 1961-1969
1,875,THE PRESIDENT'S INTELLIGENCE CHECKLIST 9 JUNE ...,FOIA,None,pdbs,5959225,RIPPUB,T,11.0,2015-09-16,2015-09-16,None,None,2064-06-09,https://www.cia.gov/library/readingroom/docs/D...,DOC_0005959225,Declassified in Part - Sanitized Copy Approved...,Declassified in Part Sanitized Copy Approved f...,20.0,President's Daily Brief 1961-1969
2,1279,THE PRESIDENT'S INTELLIGENCE REVIEW 2-5 MAY 1964,FOIA,None,pdbs,5959156,RIPPUB,T,9.0,2015-09-16,2015-09-16,None,None,2064-05-05,https://www.cia.gov/library/readingroom/docs/D...,DOC_0005959156,14 — | ee\n\g Declassified in Part - Sanitized...,14 ee \g Declassified in Part Sanitized Copy A...,19.0,President's Daily Brief 1961-1969
3,1735,THE PRESIDENT'S INTELLIGENCE CHECKLIST 18 JANU...,FOIA,None,pdbs,5992147,RIPPUB,T,8.0,2015-09-16,2015-09-16,None,None,2062-01-18,https://www.cia.gov/library/readingroom/docs/D...,DOC_0005992147,i\n— o~new Declassified In Part - Sanitized C...,i o~new Declassified In Part Sanitized Copy Ap...,4.0,President's Daily Brief 1961-1969
4,1916,THE PRESIDENT'S INTELLIGENCE CHECKLIST 12 JANU...,FOIA,None,pdbs,5992137,RIPPUB,T,7.0,2015-09-16,2015-09-16,None,None,2062-01-12,https://www.cia.gov/library/readingroom/docs/D...,DOC_0005992137,Declassified in Part - Sanitized Copy Approved...,Declassified in Part Sanitized Copy Approved f...,9.0,President's Daily Brief 1961-1969